'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WsCotaDolar
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS", ConfigurationName:="WsCotaDolar.FachadaWSSGS")>  _
    Public Interface FachadaWSSGS
        
        'CODEGEN: Gerando contrato de mensagem porque o namespace do conteúdo (http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br) da mensagem getValoresSeriesVORequest não corresponde ao valor padrão (https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS)
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function getValoresSeriesVO(ByVal request As WsCotaDolar.getValoresSeriesVORequest) As WsCotaDolar.getValoresSeriesVOResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function getValoresSeriesVOAsync(ByVal request As WsCotaDolar.getValoresSeriesVORequest) As System.Threading.Tasks.Task(Of WsCotaDolar.getValoresSeriesVOResponse)
        
        'CODEGEN: Gerando contrato de mensagem porque o namespace do conteúdo (http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br) da mensagem getUltimosValoresSerieVORequest não corresponde ao valor padrão (https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS)
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function getUltimosValoresSerieVO(ByVal request As WsCotaDolar.getUltimosValoresSerieVORequest) As WsCotaDolar.getUltimosValoresSerieVOResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function getUltimosValoresSerieVOAsync(ByVal request As WsCotaDolar.getUltimosValoresSerieVORequest) As System.Threading.Tasks.Task(Of WsCotaDolar.getUltimosValoresSerieVOResponse)
        
        'CODEGEN: Gerando contrato de mensagem porque o namespace do conteúdo (http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br) da mensagem getValoresSeriesXMLRequest não corresponde ao valor padrão (https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS)
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function getValoresSeriesXML(ByVal request As WsCotaDolar.getValoresSeriesXMLRequest) As WsCotaDolar.getValoresSeriesXMLResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function getValoresSeriesXMLAsync(ByVal request As WsCotaDolar.getValoresSeriesXMLRequest) As System.Threading.Tasks.Task(Of WsCotaDolar.getValoresSeriesXMLResponse)
        
        'CODEGEN: Gerando contrato de mensagem porque o namespace do conteúdo (http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br) da mensagem getUltimoValorVORequest não corresponde ao valor padrão (https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS)
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function getUltimoValorVO(ByVal request As WsCotaDolar.getUltimoValorVORequest) As WsCotaDolar.getUltimoValorVOResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function getUltimoValorVOAsync(ByVal request As WsCotaDolar.getUltimoValorVORequest) As System.Threading.Tasks.Task(Of WsCotaDolar.getUltimoValorVOResponse)
        
        'CODEGEN: Gerando contrato de mensagem porque o namespace do conteúdo (http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br) da mensagem getUltimoValorXMLRequest não corresponde ao valor padrão (https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS)
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function getUltimoValorXML(ByVal request As WsCotaDolar.getUltimoValorXMLRequest) As WsCotaDolar.getUltimoValorXMLResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function getUltimoValorXMLAsync(ByVal request As WsCotaDolar.getUltimoValorXMLRequest) As System.Threading.Tasks.Task(Of WsCotaDolar.getUltimoValorXMLResponse)
        
        'CODEGEN: Gerando contrato de mensagem porque o namespace do conteúdo (http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br) da mensagem getValorRequest não corresponde ao valor padrão (https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS)
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function getValor(ByVal request As WsCotaDolar.getValorRequest) As WsCotaDolar.getValorResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function getValorAsync(ByVal request As WsCotaDolar.getValorRequest) As System.Threading.Tasks.Task(Of WsCotaDolar.getValorResponse)
        
        'CODEGEN: Gerando contrato de mensagem porque o namespace do conteúdo (http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br) da mensagem getValorEspecialRequest não corresponde ao valor padrão (https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS)
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function getValorEspecial(ByVal request As WsCotaDolar.getValorEspecialRequest) As WsCotaDolar.getValorEspecialResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function getValorEspecialAsync(ByVal request As WsCotaDolar.getValorEspecialRequest) As System.Threading.Tasks.Task(Of WsCotaDolar.getValorEspecialResponse)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://comum.ws.casosdeuso.sgs.pec.bcb.gov.br")>  _
    Partial Public Class WSSerieVO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private anoFimField As Integer
        
        Private anoInicioField As Integer
        
        Private avisoField As String
        
        Private diaFimField As Integer
        
        Private diaInicioField As Integer
        
        Private especialField As Boolean
        
        Private fonteField As String
        
        Private fullNameField As String
        
        Private gestorProprietarioField As String
        
        Private mesFimField As Integer
        
        Private mesInicioField As Integer
        
        Private nomeAbreviadoField As String
        
        Private nomeCompletoField As String
        
        Private oidField As Long
        
        Private periodicidadeField As String
        
        Private periodicidadeSiglaField As String
        
        Private possuiBloqueiosField As Boolean
        
        Private publicaField As Boolean
        
        Private shortNameField As String
        
        Private ultimoValorField As WSValorSerieVO
        
        Private unidadePadraoField As String
        
        Private unidadePadraoInglesField As String
        
        Private valorDiaNaoUtilField As Boolean
        
        Private valoresField() As WSValorSerieVO
        
        '''<remarks/>
        Public Property anoFim() As Integer
            Get
                Return Me.anoFimField
            End Get
            Set
                Me.anoFimField = value
                Me.RaisePropertyChanged("anoFim")
            End Set
        End Property
        
        '''<remarks/>
        Public Property anoInicio() As Integer
            Get
                Return Me.anoInicioField
            End Get
            Set
                Me.anoInicioField = value
                Me.RaisePropertyChanged("anoInicio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property aviso() As String
            Get
                Return Me.avisoField
            End Get
            Set
                Me.avisoField = value
                Me.RaisePropertyChanged("aviso")
            End Set
        End Property
        
        '''<remarks/>
        Public Property diaFim() As Integer
            Get
                Return Me.diaFimField
            End Get
            Set
                Me.diaFimField = value
                Me.RaisePropertyChanged("diaFim")
            End Set
        End Property
        
        '''<remarks/>
        Public Property diaInicio() As Integer
            Get
                Return Me.diaInicioField
            End Get
            Set
                Me.diaInicioField = value
                Me.RaisePropertyChanged("diaInicio")
            End Set
        End Property
        
        '''<remarks/>
        Public Property especial() As Boolean
            Get
                Return Me.especialField
            End Get
            Set
                Me.especialField = value
                Me.RaisePropertyChanged("especial")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property fonte() As String
            Get
                Return Me.fonteField
            End Get
            Set
                Me.fonteField = value
                Me.RaisePropertyChanged("fonte")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property fullName() As String
            Get
                Return Me.fullNameField
            End Get
            Set
                Me.fullNameField = value
                Me.RaisePropertyChanged("fullName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property gestorProprietario() As String
            Get
                Return Me.gestorProprietarioField
            End Get
            Set
                Me.gestorProprietarioField = value
                Me.RaisePropertyChanged("gestorProprietario")
            End Set
        End Property
        
        '''<remarks/>
        Public Property mesFim() As Integer
            Get
                Return Me.mesFimField
            End Get
            Set
                Me.mesFimField = value
                Me.RaisePropertyChanged("mesFim")
            End Set
        End Property
        
        '''<remarks/>
        Public Property mesInicio() As Integer
            Get
                Return Me.mesInicioField
            End Get
            Set
                Me.mesInicioField = value
                Me.RaisePropertyChanged("mesInicio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property nomeAbreviado() As String
            Get
                Return Me.nomeAbreviadoField
            End Get
            Set
                Me.nomeAbreviadoField = value
                Me.RaisePropertyChanged("nomeAbreviado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property nomeCompleto() As String
            Get
                Return Me.nomeCompletoField
            End Get
            Set
                Me.nomeCompletoField = value
                Me.RaisePropertyChanged("nomeCompleto")
            End Set
        End Property
        
        '''<remarks/>
        Public Property oid() As Long
            Get
                Return Me.oidField
            End Get
            Set
                Me.oidField = value
                Me.RaisePropertyChanged("oid")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property periodicidade() As String
            Get
                Return Me.periodicidadeField
            End Get
            Set
                Me.periodicidadeField = value
                Me.RaisePropertyChanged("periodicidade")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property periodicidadeSigla() As String
            Get
                Return Me.periodicidadeSiglaField
            End Get
            Set
                Me.periodicidadeSiglaField = value
                Me.RaisePropertyChanged("periodicidadeSigla")
            End Set
        End Property
        
        '''<remarks/>
        Public Property possuiBloqueios() As Boolean
            Get
                Return Me.possuiBloqueiosField
            End Get
            Set
                Me.possuiBloqueiosField = value
                Me.RaisePropertyChanged("possuiBloqueios")
            End Set
        End Property
        
        '''<remarks/>
        Public Property publica() As Boolean
            Get
                Return Me.publicaField
            End Get
            Set
                Me.publicaField = value
                Me.RaisePropertyChanged("publica")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property shortName() As String
            Get
                Return Me.shortNameField
            End Get
            Set
                Me.shortNameField = value
                Me.RaisePropertyChanged("shortName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property ultimoValor() As WSValorSerieVO
            Get
                Return Me.ultimoValorField
            End Get
            Set
                Me.ultimoValorField = value
                Me.RaisePropertyChanged("ultimoValor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property unidadePadrao() As String
            Get
                Return Me.unidadePadraoField
            End Get
            Set
                Me.unidadePadraoField = value
                Me.RaisePropertyChanged("unidadePadrao")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property unidadePadraoIngles() As String
            Get
                Return Me.unidadePadraoInglesField
            End Get
            Set
                Me.unidadePadraoInglesField = value
                Me.RaisePropertyChanged("unidadePadraoIngles")
            End Set
        End Property
        
        '''<remarks/>
        Public Property valorDiaNaoUtil() As Boolean
            Get
                Return Me.valorDiaNaoUtilField
            End Get
            Set
                Me.valorDiaNaoUtilField = value
                Me.RaisePropertyChanged("valorDiaNaoUtil")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property valores() As WSValorSerieVO()
            Get
                Return Me.valoresField
            End Get
            Set
                Me.valoresField = value
                Me.RaisePropertyChanged("valores")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://comum.ws.casosdeuso.sgs.pec.bcb.gov.br")>  _
    Partial Public Class WSValorSerieVO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private anoField As Integer
        
        Private anoFimField As Integer
        
        Private bloqueadoField As Boolean
        
        Private bloqueioLiberadoField As Boolean
        
        Private diaField As Integer
        
        Private diaFimField As Integer
        
        Private mesField As Integer
        
        Private mesFimField As Integer
        
        Private oidField As Long
        
        Private oidSerieField As Long
        
        Private svalorField As String
        
        Private valorField As System.Nullable(Of Decimal)
        
        '''<remarks/>
        Public Property ano() As Integer
            Get
                Return Me.anoField
            End Get
            Set
                Me.anoField = value
                Me.RaisePropertyChanged("ano")
            End Set
        End Property
        
        '''<remarks/>
        Public Property anoFim() As Integer
            Get
                Return Me.anoFimField
            End Get
            Set
                Me.anoFimField = value
                Me.RaisePropertyChanged("anoFim")
            End Set
        End Property
        
        '''<remarks/>
        Public Property bloqueado() As Boolean
            Get
                Return Me.bloqueadoField
            End Get
            Set
                Me.bloqueadoField = value
                Me.RaisePropertyChanged("bloqueado")
            End Set
        End Property
        
        '''<remarks/>
        Public Property bloqueioLiberado() As Boolean
            Get
                Return Me.bloqueioLiberadoField
            End Get
            Set
                Me.bloqueioLiberadoField = value
                Me.RaisePropertyChanged("bloqueioLiberado")
            End Set
        End Property
        
        '''<remarks/>
        Public Property dia() As Integer
            Get
                Return Me.diaField
            End Get
            Set
                Me.diaField = value
                Me.RaisePropertyChanged("dia")
            End Set
        End Property
        
        '''<remarks/>
        Public Property diaFim() As Integer
            Get
                Return Me.diaFimField
            End Get
            Set
                Me.diaFimField = value
                Me.RaisePropertyChanged("diaFim")
            End Set
        End Property
        
        '''<remarks/>
        Public Property mes() As Integer
            Get
                Return Me.mesField
            End Get
            Set
                Me.mesField = value
                Me.RaisePropertyChanged("mes")
            End Set
        End Property
        
        '''<remarks/>
        Public Property mesFim() As Integer
            Get
                Return Me.mesFimField
            End Get
            Set
                Me.mesFimField = value
                Me.RaisePropertyChanged("mesFim")
            End Set
        End Property
        
        '''<remarks/>
        Public Property oid() As Long
            Get
                Return Me.oidField
            End Get
            Set
                Me.oidField = value
                Me.RaisePropertyChanged("oid")
            End Set
        End Property
        
        '''<remarks/>
        Public Property oidSerie() As Long
            Get
                Return Me.oidSerieField
            End Get
            Set
                Me.oidSerieField = value
                Me.RaisePropertyChanged("oidSerie")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property svalor() As String
            Get
                Return Me.svalorField
            End Get
            Set
                Me.svalorField = value
                Me.RaisePropertyChanged("svalor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property valor() As System.Nullable(Of Decimal)
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
                Me.RaisePropertyChanged("valor")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getValoresSeriesVO", WrapperNamespace:="http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br", IsWrapped:=true)>  _
    Partial Public Class getValoresSeriesVORequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public in0() As Long
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public in1 As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public in2 As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal in0() As Long, ByVal in1 As String, ByVal in2 As String)
            MyBase.New
            Me.in0 = in0
            Me.in1 = in1
            Me.in2 = in2
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getValoresSeriesVOResponse", WrapperNamespace:="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS", IsWrapped:=true)>  _
    Partial Public Class getValoresSeriesVOResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public getValoresSeriesVOReturn() As WsCotaDolar.WSSerieVO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getValoresSeriesVOReturn() As WsCotaDolar.WSSerieVO)
            MyBase.New
            Me.getValoresSeriesVOReturn = getValoresSeriesVOReturn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getUltimosValoresSerieVO", WrapperNamespace:="http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br", IsWrapped:=true)>  _
    Partial Public Class getUltimosValoresSerieVORequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public in0 As Long
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public in1 As Long
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal in0 As Long, ByVal in1 As Long)
            MyBase.New
            Me.in0 = in0
            Me.in1 = in1
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getUltimosValoresSerieVOResponse", WrapperNamespace:="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS", IsWrapped:=true)>  _
    Partial Public Class getUltimosValoresSerieVOResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public getUltimosValoresSerieVOReturn As WsCotaDolar.WSSerieVO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getUltimosValoresSerieVOReturn As WsCotaDolar.WSSerieVO)
            MyBase.New
            Me.getUltimosValoresSerieVOReturn = getUltimosValoresSerieVOReturn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getValoresSeriesXML", WrapperNamespace:="http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br", IsWrapped:=true)>  _
    Partial Public Class getValoresSeriesXMLRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public in0() As Long
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public in1 As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public in2 As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal in0() As Long, ByVal in1 As String, ByVal in2 As String)
            MyBase.New
            Me.in0 = in0
            Me.in1 = in1
            Me.in2 = in2
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getValoresSeriesXMLResponse", WrapperNamespace:="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS", IsWrapped:=true)>  _
    Partial Public Class getValoresSeriesXMLResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public getValoresSeriesXMLReturn As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getValoresSeriesXMLReturn As String)
            MyBase.New
            Me.getValoresSeriesXMLReturn = getValoresSeriesXMLReturn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getUltimoValorVO", WrapperNamespace:="http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br", IsWrapped:=true)>  _
    Partial Public Class getUltimoValorVORequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public in0 As Long
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal in0 As Long)
            MyBase.New
            Me.in0 = in0
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getUltimoValorVOResponse", WrapperNamespace:="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS", IsWrapped:=true)>  _
    Partial Public Class getUltimoValorVOResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public getUltimoValorVOReturn As WsCotaDolar.WSSerieVO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getUltimoValorVOReturn As WsCotaDolar.WSSerieVO)
            MyBase.New
            Me.getUltimoValorVOReturn = getUltimoValorVOReturn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getUltimoValorXML", WrapperNamespace:="http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br", IsWrapped:=true)>  _
    Partial Public Class getUltimoValorXMLRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public in0 As Long
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal in0 As Long)
            MyBase.New
            Me.in0 = in0
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getUltimoValorXMLResponse", WrapperNamespace:="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS", IsWrapped:=true)>  _
    Partial Public Class getUltimoValorXMLResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public getUltimoValorXMLReturn As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getUltimoValorXMLReturn As String)
            MyBase.New
            Me.getUltimoValorXMLReturn = getUltimoValorXMLReturn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getValor", WrapperNamespace:="http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br", IsWrapped:=true)>  _
    Partial Public Class getValorRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public in0 As Long
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public in1 As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal in0 As Long, ByVal in1 As String)
            MyBase.New
            Me.in0 = in0
            Me.in1 = in1
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getValorResponse", WrapperNamespace:="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS", IsWrapped:=true)>  _
    Partial Public Class getValorResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public getValorReturn As Decimal
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getValorReturn As Decimal)
            MyBase.New
            Me.getValorReturn = getValorReturn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getValorEspecial", WrapperNamespace:="http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br", IsWrapped:=true)>  _
    Partial Public Class getValorEspecialRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public in0 As Long
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public in1 As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public in2 As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal in0 As Long, ByVal in1 As String, ByVal in2 As String)
            MyBase.New
            Me.in0 = in0
            Me.in1 = in1
            Me.in2 = in2
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getValorEspecialResponse", WrapperNamespace:="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS", IsWrapped:=true)>  _
    Partial Public Class getValorEspecialResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public getValorEspecialReturn As Decimal
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getValorEspecialReturn As Decimal)
            MyBase.New
            Me.getValorEspecialReturn = getValorEspecialReturn
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface FachadaWSSGSChannel
        Inherits WsCotaDolar.FachadaWSSGS, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class FachadaWSSGSClient
        Inherits System.ServiceModel.ClientBase(Of WsCotaDolar.FachadaWSSGS)
        Implements WsCotaDolar.FachadaWSSGS
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsCotaDolar_FachadaWSSGS_getValoresSeriesVO(ByVal request As WsCotaDolar.getValoresSeriesVORequest) As WsCotaDolar.getValoresSeriesVOResponse Implements WsCotaDolar.FachadaWSSGS.getValoresSeriesVO
            Return MyBase.Channel.getValoresSeriesVO(request)
        End Function
        
        Public Function getValoresSeriesVO(ByVal in0() As Long, ByVal in1 As String, ByVal in2 As String) As WsCotaDolar.WSSerieVO()
            Dim inValue As WsCotaDolar.getValoresSeriesVORequest = New WsCotaDolar.getValoresSeriesVORequest()
            inValue.in0 = in0
            inValue.in1 = in1
            inValue.in2 = in2
            Dim retVal As WsCotaDolar.getValoresSeriesVOResponse = CType(Me,WsCotaDolar.FachadaWSSGS).getValoresSeriesVO(inValue)
            Return retVal.getValoresSeriesVOReturn
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsCotaDolar_FachadaWSSGS_getValoresSeriesVOAsync(ByVal request As WsCotaDolar.getValoresSeriesVORequest) As System.Threading.Tasks.Task(Of WsCotaDolar.getValoresSeriesVOResponse) Implements WsCotaDolar.FachadaWSSGS.getValoresSeriesVOAsync
            Return MyBase.Channel.getValoresSeriesVOAsync(request)
        End Function
        
        Public Function getValoresSeriesVOAsync(ByVal in0() As Long, ByVal in1 As String, ByVal in2 As String) As System.Threading.Tasks.Task(Of WsCotaDolar.getValoresSeriesVOResponse)
            Dim inValue As WsCotaDolar.getValoresSeriesVORequest = New WsCotaDolar.getValoresSeriesVORequest()
            inValue.in0 = in0
            inValue.in1 = in1
            inValue.in2 = in2
            Return CType(Me,WsCotaDolar.FachadaWSSGS).getValoresSeriesVOAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsCotaDolar_FachadaWSSGS_getUltimosValoresSerieVO(ByVal request As WsCotaDolar.getUltimosValoresSerieVORequest) As WsCotaDolar.getUltimosValoresSerieVOResponse Implements WsCotaDolar.FachadaWSSGS.getUltimosValoresSerieVO
            Return MyBase.Channel.getUltimosValoresSerieVO(request)
        End Function
        
        Public Function getUltimosValoresSerieVO(ByVal in0 As Long, ByVal in1 As Long) As WsCotaDolar.WSSerieVO
            Dim inValue As WsCotaDolar.getUltimosValoresSerieVORequest = New WsCotaDolar.getUltimosValoresSerieVORequest()
            inValue.in0 = in0
            inValue.in1 = in1
            Dim retVal As WsCotaDolar.getUltimosValoresSerieVOResponse = CType(Me,WsCotaDolar.FachadaWSSGS).getUltimosValoresSerieVO(inValue)
            Return retVal.getUltimosValoresSerieVOReturn
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsCotaDolar_FachadaWSSGS_getUltimosValoresSerieVOAsync(ByVal request As WsCotaDolar.getUltimosValoresSerieVORequest) As System.Threading.Tasks.Task(Of WsCotaDolar.getUltimosValoresSerieVOResponse) Implements WsCotaDolar.FachadaWSSGS.getUltimosValoresSerieVOAsync
            Return MyBase.Channel.getUltimosValoresSerieVOAsync(request)
        End Function
        
        Public Function getUltimosValoresSerieVOAsync(ByVal in0 As Long, ByVal in1 As Long) As System.Threading.Tasks.Task(Of WsCotaDolar.getUltimosValoresSerieVOResponse)
            Dim inValue As WsCotaDolar.getUltimosValoresSerieVORequest = New WsCotaDolar.getUltimosValoresSerieVORequest()
            inValue.in0 = in0
            inValue.in1 = in1
            Return CType(Me,WsCotaDolar.FachadaWSSGS).getUltimosValoresSerieVOAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsCotaDolar_FachadaWSSGS_getValoresSeriesXML(ByVal request As WsCotaDolar.getValoresSeriesXMLRequest) As WsCotaDolar.getValoresSeriesXMLResponse Implements WsCotaDolar.FachadaWSSGS.getValoresSeriesXML
            Return MyBase.Channel.getValoresSeriesXML(request)
        End Function
        
        Public Function getValoresSeriesXML(ByVal in0() As Long, ByVal in1 As String, ByVal in2 As String) As String
            Dim inValue As WsCotaDolar.getValoresSeriesXMLRequest = New WsCotaDolar.getValoresSeriesXMLRequest()
            inValue.in0 = in0
            inValue.in1 = in1
            inValue.in2 = in2
            Dim retVal As WsCotaDolar.getValoresSeriesXMLResponse = CType(Me,WsCotaDolar.FachadaWSSGS).getValoresSeriesXML(inValue)
            Return retVal.getValoresSeriesXMLReturn
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsCotaDolar_FachadaWSSGS_getValoresSeriesXMLAsync(ByVal request As WsCotaDolar.getValoresSeriesXMLRequest) As System.Threading.Tasks.Task(Of WsCotaDolar.getValoresSeriesXMLResponse) Implements WsCotaDolar.FachadaWSSGS.getValoresSeriesXMLAsync
            Return MyBase.Channel.getValoresSeriesXMLAsync(request)
        End Function
        
        Public Function getValoresSeriesXMLAsync(ByVal in0() As Long, ByVal in1 As String, ByVal in2 As String) As System.Threading.Tasks.Task(Of WsCotaDolar.getValoresSeriesXMLResponse)
            Dim inValue As WsCotaDolar.getValoresSeriesXMLRequest = New WsCotaDolar.getValoresSeriesXMLRequest()
            inValue.in0 = in0
            inValue.in1 = in1
            inValue.in2 = in2
            Return CType(Me,WsCotaDolar.FachadaWSSGS).getValoresSeriesXMLAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsCotaDolar_FachadaWSSGS_getUltimoValorVO(ByVal request As WsCotaDolar.getUltimoValorVORequest) As WsCotaDolar.getUltimoValorVOResponse Implements WsCotaDolar.FachadaWSSGS.getUltimoValorVO
            Return MyBase.Channel.getUltimoValorVO(request)
        End Function
        
        Public Function getUltimoValorVO(ByVal in0 As Long) As WsCotaDolar.WSSerieVO
            Dim inValue As WsCotaDolar.getUltimoValorVORequest = New WsCotaDolar.getUltimoValorVORequest()
            inValue.in0 = in0
            Dim retVal As WsCotaDolar.getUltimoValorVOResponse = CType(Me,WsCotaDolar.FachadaWSSGS).getUltimoValorVO(inValue)
            Return retVal.getUltimoValorVOReturn
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsCotaDolar_FachadaWSSGS_getUltimoValorVOAsync(ByVal request As WsCotaDolar.getUltimoValorVORequest) As System.Threading.Tasks.Task(Of WsCotaDolar.getUltimoValorVOResponse) Implements WsCotaDolar.FachadaWSSGS.getUltimoValorVOAsync
            Return MyBase.Channel.getUltimoValorVOAsync(request)
        End Function
        
        Public Function getUltimoValorVOAsync(ByVal in0 As Long) As System.Threading.Tasks.Task(Of WsCotaDolar.getUltimoValorVOResponse)
            Dim inValue As WsCotaDolar.getUltimoValorVORequest = New WsCotaDolar.getUltimoValorVORequest()
            inValue.in0 = in0
            Return CType(Me,WsCotaDolar.FachadaWSSGS).getUltimoValorVOAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsCotaDolar_FachadaWSSGS_getUltimoValorXML(ByVal request As WsCotaDolar.getUltimoValorXMLRequest) As WsCotaDolar.getUltimoValorXMLResponse Implements WsCotaDolar.FachadaWSSGS.getUltimoValorXML
            Return MyBase.Channel.getUltimoValorXML(request)
        End Function
        
        Public Function getUltimoValorXML(ByVal in0 As Long) As String
            Dim inValue As WsCotaDolar.getUltimoValorXMLRequest = New WsCotaDolar.getUltimoValorXMLRequest()
            inValue.in0 = in0
            Dim retVal As WsCotaDolar.getUltimoValorXMLResponse = CType(Me,WsCotaDolar.FachadaWSSGS).getUltimoValorXML(inValue)
            Return retVal.getUltimoValorXMLReturn
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsCotaDolar_FachadaWSSGS_getUltimoValorXMLAsync(ByVal request As WsCotaDolar.getUltimoValorXMLRequest) As System.Threading.Tasks.Task(Of WsCotaDolar.getUltimoValorXMLResponse) Implements WsCotaDolar.FachadaWSSGS.getUltimoValorXMLAsync
            Return MyBase.Channel.getUltimoValorXMLAsync(request)
        End Function
        
        Public Function getUltimoValorXMLAsync(ByVal in0 As Long) As System.Threading.Tasks.Task(Of WsCotaDolar.getUltimoValorXMLResponse)
            Dim inValue As WsCotaDolar.getUltimoValorXMLRequest = New WsCotaDolar.getUltimoValorXMLRequest()
            inValue.in0 = in0
            Return CType(Me,WsCotaDolar.FachadaWSSGS).getUltimoValorXMLAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsCotaDolar_FachadaWSSGS_getValor(ByVal request As WsCotaDolar.getValorRequest) As WsCotaDolar.getValorResponse Implements WsCotaDolar.FachadaWSSGS.getValor
            Return MyBase.Channel.getValor(request)
        End Function
        
        Public Function getValor(ByVal in0 As Long, ByVal in1 As String) As Decimal
            Dim inValue As WsCotaDolar.getValorRequest = New WsCotaDolar.getValorRequest()
            inValue.in0 = in0
            inValue.in1 = in1
            Dim retVal As WsCotaDolar.getValorResponse = CType(Me,WsCotaDolar.FachadaWSSGS).getValor(inValue)
            Return retVal.getValorReturn
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsCotaDolar_FachadaWSSGS_getValorAsync(ByVal request As WsCotaDolar.getValorRequest) As System.Threading.Tasks.Task(Of WsCotaDolar.getValorResponse) Implements WsCotaDolar.FachadaWSSGS.getValorAsync
            Return MyBase.Channel.getValorAsync(request)
        End Function
        
        Public Function getValorAsync(ByVal in0 As Long, ByVal in1 As String) As System.Threading.Tasks.Task(Of WsCotaDolar.getValorResponse)
            Dim inValue As WsCotaDolar.getValorRequest = New WsCotaDolar.getValorRequest()
            inValue.in0 = in0
            inValue.in1 = in1
            Return CType(Me,WsCotaDolar.FachadaWSSGS).getValorAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsCotaDolar_FachadaWSSGS_getValorEspecial(ByVal request As WsCotaDolar.getValorEspecialRequest) As WsCotaDolar.getValorEspecialResponse Implements WsCotaDolar.FachadaWSSGS.getValorEspecial
            Return MyBase.Channel.getValorEspecial(request)
        End Function
        
        Public Function getValorEspecial(ByVal in0 As Long, ByVal in1 As String, ByVal in2 As String) As Decimal
            Dim inValue As WsCotaDolar.getValorEspecialRequest = New WsCotaDolar.getValorEspecialRequest()
            inValue.in0 = in0
            inValue.in1 = in1
            inValue.in2 = in2
            Dim retVal As WsCotaDolar.getValorEspecialResponse = CType(Me,WsCotaDolar.FachadaWSSGS).getValorEspecial(inValue)
            Return retVal.getValorEspecialReturn
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsCotaDolar_FachadaWSSGS_getValorEspecialAsync(ByVal request As WsCotaDolar.getValorEspecialRequest) As System.Threading.Tasks.Task(Of WsCotaDolar.getValorEspecialResponse) Implements WsCotaDolar.FachadaWSSGS.getValorEspecialAsync
            Return MyBase.Channel.getValorEspecialAsync(request)
        End Function
        
        Public Function getValorEspecialAsync(ByVal in0 As Long, ByVal in1 As String, ByVal in2 As String) As System.Threading.Tasks.Task(Of WsCotaDolar.getValorEspecialResponse)
            Dim inValue As WsCotaDolar.getValorEspecialRequest = New WsCotaDolar.getValorEspecialRequest()
            inValue.in0 = in0
            inValue.in1 = in1
            inValue.in2 = in2
            Return CType(Me,WsCotaDolar.FachadaWSSGS).getValorEspecialAsync(inValue)
        End Function
    End Class
End Namespace
